#!/usr/bin/env python3
# coding: utf-8

FEATURE_LABELS = {
    "m1_low_pos": "1分钟最低点所在bar序号",
    "m1_low_pos_ratio": "1分钟最低点出现位置占全天比例",
    "m1_low_before_last_quarter": "1分钟最低点是否出现在最后四分之一天之前",
    "m1_rebound_to_close": "1分钟最低点到收盘反弹幅度",
    "m1_rebound_to_high_after_low": "1分钟最低点到后续最高点反弹幅度",
    "m1_post_low_min_return": "1分钟低点后再次下探幅度",
    "m1_close_in_range": "1分钟收盘在日内振幅中的位置",
    "m1_day_range": "1分钟层面全天振幅",
    "m1_close_vs_open": "1分钟收盘相对开盘涨跌幅",
    "m1_up_close_streak_after_low": "1分钟低点后连续抬高收盘的最长根数",
    "m1_up_bar_ratio_after_low": "1分钟低点后阳线占比",
    "m1_volume_ratio_after_low": "1分钟低点后平均成交量相对低点前变化",
    "m5_low_pos": "5分钟最低点所在bar序号",
    "m5_low_pos_ratio": "5分钟最低点出现位置占全天比例",
    "m5_low_before_last_quarter": "5分钟最低点是否出现在最后四分之一天之前",
    "m5_rebound_to_close": "5分钟最低点到收盘反弹幅度",
    "m5_rebound_to_high_after_low": "5分钟最低点到后续最高点反弹幅度",
    "m5_post_low_min_return": "5分钟低点后再次下探幅度",
    "m5_close_in_range": "5分钟收盘在日内振幅中的位置",
    "m5_day_range": "5分钟层面全天振幅",
    "m5_close_vs_open": "5分钟收盘相对开盘涨跌幅",
    "m5_up_close_streak_after_low": "5分钟低点后连续抬高收盘的最长根数",
    "m5_up_bar_ratio_after_low": "5分钟低点后阳线占比",
    "m5_volume_ratio_after_low": "5分钟低点后平均成交量相对低点前变化",
    "m30_low_pos": "30分钟最低点所在bar序号",
    "m30_low_pos_ratio": "30分钟最低点出现位置占全天比例",
    "m30_low_before_last_quarter": "30分钟最低点是否出现在最后四分之一天之前",
    "m30_rebound_to_close": "30分钟最低点到收盘反弹幅度",
    "m30_rebound_to_high_after_low": "30分钟最低点到后续最高点反弹幅度",
    "m30_post_low_min_return": "30分钟低点后再次下探幅度",
    "m30_close_in_range": "30分钟收盘在日内振幅中的位置",
    "m30_day_range": "30分钟层面全天振幅",
    "m30_close_vs_open": "30分钟收盘相对开盘涨跌幅",
    "m30_up_close_streak_after_low": "30分钟低点后连续抬高收盘的最长根数",
    "m30_up_bar_ratio_after_low": "30分钟低点后阳线占比",
    "m30_volume_ratio_after_low": "30分钟低点后平均成交量相对低点前变化",
    "drawdown_from_high_5": "相对近5日高点回撤",
    "drawdown_from_high_10": "相对近10日高点回撤",
    "drawdown_from_high_20": "相对近20日高点回撤",
    "down_days_last3": "近3日阴线数",
    "down_days_last5": "近5日阴线数",
    "volatility_5": "近5日收益波动率",
    "volatility_10": "近10日收益波动率",
    "ret_1d": "近1日涨跌幅",
    "ret_3d": "近3日涨跌幅",
    "ret_5d": "近5日涨跌幅",
    "close_vs_ma5": "收盘相对5日均线偏离",
    "close_vs_ma20": "收盘相对20日均线偏离",
    "vol_ratio_5": "成交量相对5日均量变化",
    "intraday_range": "当日振幅",
    "close_in_day_range": "收盘在当日振幅中的位置",
    "lower_shadow_ratio": "下影线占当日振幅比例",
    "upper_shadow_ratio": "上影线占当日振幅比例",
    "gap_from_prev_close": "开盘相对前收跳空幅度",
    "low_vs_ma20": "最低价相对20日均线偏离",
    "rsi6": "RSI(6)",
}


def feature_label(feature_name):
    return FEATURE_LABELS.get(feature_name, feature_name)
